### PR TITLE
SmartOS build fixes

### PR DESCRIPTION
**Pull request by hrosenfeld**
These are a bunch of small fixes that are needed to build on SmartOS. I also verified it still builds correctly on OI.

### CODE REVIEW

**Comment by gwr** [comment]
Did you check that running:
  usr/src/common/libdrm/Check-patches
shows only the expected output?

**Comment by gwr** [comment]
Is freedreno picking up a linux/fb.h from somewhere?  If so, where?

**Comment by hrosenfeld** [comment]
Did run Check-patches now and the output looks as expected.

I removed the include for linux/fb.h as it's not there. It is apparently not needed, it builds fine without it and the resulting library has no extra undefined symbols or anything. wsdiff output also looked sane, I think the differences I saw came from gcc being non-deterministic.

**Comment by gwr** [comment]
OK, thanks.  That was hard to see from the diff of the patch.
Go ahead and push this.  Thanks.

**Comment by xen0l** [comment]
Changes are pushed to master. Can we close this PR? 

Future note: PRs can be merged without creating a merge commit directly via 'Rebase and merge' action.

**Pull request closed without merging**
