### PR TITLE
Add sys/queue.h from illumos commit 710f7c23e0

### PR DESCRIPTION
**Pull request by gwr**
Avoids dealing with some inconvenient later changes.

### CODE REVIEW

**Comment by pyhalov** [comment]
Do I understand correctly that after this change we just use internal queue.h copy? 
This seems to be a valid workaround, but seems to me a bit unfortunate as long-term solution. 
What other options do we have? 
I see at least two other options:

- do s/container_of/__containerof/ in illumos-gate sys/queue.h (and other code) to match BSD (https://github.com/freebsd/freebsd/blob/master/sys/sys/queue.h) and avoid namespace pollution;
- just do in https://github.com/illumos/gfx-drm/blob/master/usr/src/uts/common/drm/drm_linux_list.h#L52 something like
```
#ifdef container_of
#undef container_of
#endif
```
(unfortunately, this likely will break queue.h consumers, so first solution seems to be a bit cleaner.

**Comment by pyhalov** [comment]
@tsoome, what do you think about first option?

**Comment by jclulow** [comment]
Let's not make a vendored copy of `sys/queue.h`, please.

I've been discussing with Toomas, and I think we're in rough agreement on an approach to fixing this issue on the `illumos-gate` side:

- rename `containerof()` in our header to `__containerof()` as it is on FreeBSD
- move the definition of `__containerof()` to `sys/containerof.h`, which would be a file that contained only that definition

Then, we can use the same definition all over the gate, including in `sys/queue.h`, without the side effect of namespace pollution for consumers.

Does that seem reasonable?

**Comment by pyhalov** [comment]
Why do you want to introduce a separate header for this (instead of using existing sys/sysmacros.h)?

**Comment by jclulow** [comment]
> Why do you want to introduce a separate header for this (instead of using existing sys/sysmacros.h)?

Chiefly to allow us to use a common definition for `__containerof()` without dragging in the other definitions that `sys/sysmacros.h`.  This issue is one of conflict between definitions we're making as part of our implementation of `sys/queue.h` and third party consumers of that file.  In order to avoid that kind of problem, we really don't want to introduce _any_ possible conflicts in our `sys/queue.h`, so: let's put it in a new file which _just_ contains this definition.

**Comment by pyhalov** [comment]
This seems to be reasonable.

**Comment by gwr** [comment]
> Why do you want to introduce a separate header for this (instead of using existing sys/sysmacros.h)?

Because it's simply easier if this gate isolates itself against such changes (for now anyway).
This keeps gfx-drm provably unchanged (in what it builds).

**Comment by gwr** [comment]
To  be clear,  this is NOT the place for the container_of discussion.
This review is just about:  Make gfx-drm build again, independent of what illumos gate provides for sys/queue.h

**Comment by gwr** [comment]
> Let's not make a vendored copy of `sys/queue.h`, please.
> 
> I've been discussing with Toomas, and I think we're in rough agreement on an approach to fixing this issue on the `illumos-gate` side:
> 
> * rename `containerof()` in our header to `__containerof()` as it is on FreeBSD
> * move the definition of `__containerof()` to `sys/containerof.h`, which would be a file that contained only that definition
> 
> Then, we can use the same definition all over the gate, including in `sys/queue.h`, without the side effect of namespace pollution for consumers.
> 
> Does that seem reasonable?

I'm surprised to see so much desire for using "just one true copy" of queue.h
when it's not that big a file, nor one that's needed much change over time...
(The illumos one hasn't needed change in eight years.)

**Pull request closed without merging**
